### ISSUE TITLE
lab2 

### ISSUE THREAD

**Issue by Andrewbooq** [NuraMun/pp2#1]
Принял приглашение.
Как будете готовы показать код или возникнут вопросы - пишите об этом, например в комментарии к какому-нибудь issue. Мне приходит уведомление, и я, как будет время, посмотрю.

**Comment by NuraMun** [comment]
Посмотрите последние изменения, пожалуйста

**Comment by Andrewbooq** [comment]
Хороший прогресс, нужно немного привести в порядок код.

1 В конструкторе `threadsPool::threadsPool()` есть мьютекс `lock_guard<mutex> M(m);`
Что он делает? В какой момент происходит ожидание и блокировка?

2 `cntThreads = thread::hardware_concurrency();` нужно вызывать в конструкторе. Из .h не надо звать, там интерфейс, кода не должно быть

3 `threadsPool::GetThreads()` должна возвращать значение переменной `cntThreads` вызывать `hardware_concurrency` каждый раз не имеет смысла

4 Что будет если `hardware_concurrency` вернет 0 ?

5 Вывод программы не особо информативный. Нужно добавить немного пояснений, что считаем, как считаем,....

6 Не хватает условия завершения программы. Т.е. программа отработала, вывела результат на экран. Мы еще что-то можем выполнить? другие рассчеты? нужно ли продолжать висеть? или нужно как-то завершиться.

7 В остальном всё отлично, нужно еще `Makefile` сделать, для сборки под Linux.

8 Зачем у вас конвертирование типов:
```
size_t cntThreads. 
int n = pool.GetThreads();
size_t какой тип? знаковый? а int?
```

Напомните, покажу как отлаживать проблемы зависания в многопоточном приложении

**Comment by Andrewbooq** [comment]
Не совсем понял что мы считаем. Изменил добавление вызова в очередь
`pool.passQ(Binet, i*10);`
и вывод через `printf` сделал
получаю вот такой результат
```
Number Threads: 8
0.000000
832040.000000
190392490709135.437500
102334155.000000
55.000000
12586269025.000019
1548008755920.002930
6765.000000
```
что-то здесь не так, не похоже это на числа Фибоначчи

**Comment by Andrewbooq** [comment]
Вот как раз то, о чём я говорил, про информативность вывода. Если сделать вывод вот так
```
printf ("Fibonachi value for %d element = %lf\n", n, f);
```
то вывод программы становится более понятным
```
Number Threads: 8
Fibonachi value for 0 element = 0.000000
Fibonachi value for 20 element = 6765.000000
Fibonachi value for 40 element = 102334155.000000
Fibonachi value for 60 element = 1548008755920.002930
Fibonachi value for 50 element = 12586269025.000019
Fibonachi value for 30 element = 832040.000000
Fibonachi value for 70 element = 190392490709135.437500
Fibonachi value for 10 element = 55.000000
```
А здесь можно проверить https://calculatorian.com/ru/other/fibonacci-numbers

Но все равно, не совсем верно. Числа Фибоначчи это ряд натуральных чисел, не числа с плавающей точкой.

**Comment by Andrewbooq** [comment]
Я немного усложнил математику, иначе у меня оочень быстро считается. 
```
void Binet(int n)
{
    double f { 0.0 };
    for (size_t i = 0; i < 1000000; ++i)
    {
        double fff = (pow(((1 + sqrt(5)) / 2), n) - pow((1 - (1 + sqrt(5)) / 2), n)) / sqrt(5);
        
        for (size_t j = 0; j < 1000; ++j)
        {
            fff = sqrt(fff * fff);
        }

        f += fff;
    }
    f = f / 1000000.0;
    printf ("Fibonachi value for %d element = %lf\n", n, f);
}
```

**Comment by NuraMun** [comment]
Исправила последние ваши замечания и добавила Makefile

**Comment by Andrewbooq** [comment]
Проверь, пожалуйста, что все изменения залиты. Или не всё залито на гитхаб или не все замечания исправлены.

**Comment by NuraMun** [comment]
Залила последние изменения.
1-3 Исправила до этого
4 Исправила сейчас. Добавила вывод сообщения о том, что если вернется 0, то программа не выполнится, в обратном же случае вывести кол-во потоков и зайти в цикл.
5 Есть информативный вывод
6 Программа завершает свою работу теперь
7 Makefile есть
8 Исправлено

**Comment by Andrewbooq** [comment]
Хорошо. Давай тогда так. Смотрю код прям на гитхабе. Я всё же хотел бы увидеть ответ на свой вопрос.
1 В конструкторе threadsPool::threadsPool() есть мьютекс lock_guard<mutex> M(m);
Так же есть в деструкторе unique_lock<std::mutex> M1(m);
Что они делают? В какой момент происходит ожидание и блокировка? Что такое lock_guard, что такое unique_lock и чем они отличаются?
2 Исправлено
3 threadsPool::GetThreads() должна возвращать значение переменной cntThreads вызывать hardware_concurrency каждый раз не имеет смысла.
4 Исправлено, согласен
5 Ну пусть будет, допустим. Исправлено.
6 Согласен
7 Согласен
8 Частично, всё еще вижу ворнинги о несоответствии типов
![image](https://github.com/user-attachments/assets/feac886c-c842-44ed-b9fa-4c76dec955ca)

**Comment by Andrewbooq** [comment]
Всё еще жду, пиши. До пт надо сделать, чтобы сдать лабу.

**Comment by NuraMun** [comment]
Здравствуйте, я обновила файлы свои
1) lock_guard  простая обертка для мьютекса, которая блокирует мьютекс в момент создания и разблокирует его в момент уничтожения. unique_lock же более гибкий, и дает дополнительные функции, такие как возможность разблокировать мьютекс вручную, повторно блокировать. Скорее всего здесь вообще они не имеют какой-либо полезности. Потому что в конструкторе lock_guard блокирует мьютекс m, но он не используется для синхронизации каких-либо операций, так как после создания объекта lock_guard сразу выходит из области видимости, и мьютекс разблокируется.  А в деструкторе unique_lock блокирует мьютекс m, но также не используется, так как никакие операции, требующие блокировки мьютекса, не происходят после его создания. В общем, я их убрала)
3)
8) Исправлено, в main

**Comment by NuraMun** [comment]
Здравствуйте, я обновила файлы свои

1.lock_guard простая обертка для мьютекса, которая блокирует мьютекс в момент создания и разблокирует его в момент уничтожения. unique_lock же более гибкий, и дает дополнительные функции, такие как возможность разблокировать мьютекс вручную, повторно блокировать. Скорее всего здесь вообще они не имеют какой-либо полезности. Потому что в конструкторе lock_guard блокирует мьютекс m, но он не используется для синхронизации каких-либо операций, так как после создания объекта lock_guard сразу выходит из области видимости, и мьютекс разблокируется. А в деструкторе unique_lock блокирует мьютекс m, но также не используется, так как никакие операции, требующие блокировки мьютекса, не происходят после его создания. В общем, я их убрала)
3. Увидела, изменила в конструкторе threadsPool()  cntThreads = GetThreads(), использую метод для нахождения количества потоков;
8.Исправлено, в main в цикле тип переменной i исправлен с int на unsigned int

**Comment by Andrewbooq** [comment]
1. Абсолютно верно. лок в конструкторе (при создании объекта), анлок при разрушении (при выходе их области видимости/выходе из функции). Я именно поэтому и мучал тебя. Что мьютексы бессмысленно создавались там, где они не нужны (а точнее ничего не происходило в месте их использования). 
3. Неа, не так. Надо наоборот. В конструкторе один раз спрашивать у системы значение и сохранять в локальную переменную
```
cntThreads = thread::hardware_concurrency()
```
а в GetThreads просто возвращать сохраненное значение
```
unsigned int threadsPool::GetThreads() {
    return cntThreads ;
}
```
8. Ладно пусть так будет, ворнингов нет. Но вообще лично я за однообразие. Если ты используешь в циклах for - `size_t` (который тоже беззнаковый), то его надо везде использовать, если используешь `unsigned int`, то значит его везде используй. А вообще, я рекомендую полностью уйти от `size_t`, потому что это платформозависимый тип. В винде это unsigned long (32 bit), а в Linux это unsigned long long (64 bit). В следующей лабе могут возникнуть проблемы опять.
Лучше всего использовать даже не `unsigned int`, а тип с явной размерностью - `uint32_t` - это точно всегда беззнаковый и всегда явно 32 бита на любой платформе.

**Comment by Andrewbooq** [comment]
доделай, пожалуйста, пункт 2, можно мне не присылать. Можно приступать к последней Лабораторной (только не в этой, пожалуйста, сделай копию в папочку pp3 например). Если не помнишь задание - скажи, напишу.
Эту работу можно сдавать.
Для сдачи работы пообщаемся по материалам лекций, связанных с этой лабораторной. По моим заметкам тебя не было на 5, 6 лекциях, вот темы этих лекций:
- Защита разделяемых данных во время инициализации
- Защита редко обновляемых структур данных
- Рекурсивная блокировка
- Синхронизация параллельных операций:
  1 Ожидание события или иного условия:
    а Ожидание условия с помощью условных переменных

Я повторял пройденный материал на лекции, поэтому совсем немного
